import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { env } from "./env";

/**
 * S3-compatible storage (SPEC §9). MinIO in dev, Railway MinIO in production —
 * the same API either way.
 *
 * The bucket is PRIVATE and has no public policy. Nothing here ever hands the
 * storage host to a browser; `/api/media/[...key]` issues a short-lived
 * presigned redirect instead, so the origin stays ours.
 *
 * Server-only: this module reads credentials and must never be imported from a
 * client script (AGENT §4).
 */
const client = new S3Client({
  region: env.S3_REGION,
  endpoint: env.S3_ENDPOINT,
  // MinIO serves buckets as path segments rather than subdomains.
  forcePathStyle: env.S3_FORCE_PATH_STYLE,
  credentials: {
    accessKeyId: env.S3_ACCESS_KEY_ID,
    secretAccessKey: env.S3_SECRET_ACCESS_KEY,
  },
});

/** SPEC §9 — 5-minute TTL on the presigned URL. */
export const PRESIGN_TTL_SECONDS = 300;

/**
 * How long a browser may cache the 302 itself.
 *
 * MUST stay below PRESIGN_TTL_SECONDS. A cached redirect replays a stale
 * `Location`, and the presigned URL behind it 403s once its signature expires —
 * so a redirect that outlives its own signature serves broken images to
 * returning visitors, invisibly, until the redirect cache expires too.
 *
 * Derived rather than written twice; the invariant is asserted in the tests.
 */
export const REDIRECT_CACHE_SECONDS = PRESIGN_TTL_SECONDS - 60;

export function presignGet(
  key: string,
  bucket = env.S3_BUCKET,
): Promise<string> {
  return getSignedUrl(
    client,
    new GetObjectCommand({ Bucket: bucket, Key: key }),
    {
      expiresIn: PRESIGN_TTL_SECONDS,
    },
  );
}

/**
 * Keys are generated by the upload pipeline (#28) as
 * `projects/{projectId}/{ulid}-{width}.{ext}` — never a client-supplied filename
 * (SPEC §9).
 *
 * This is a shape check, not the authorisation: the route still requires a
 * matching `MediaAsset` row. It exists so a traversal or absolute path is
 * rejected before it can reach the S3 client at all, and so the rejection is
 * cheap. AGENT §3: nothing user-controlled reaches an outbound URL unvalidated.
 */
const KEY_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._/-]*$/;

export function isSafeKey(key: string): boolean {
  if (key.length === 0 || key.length > 512) return false;
  // Traversal, absolute paths, protocol-relative, backslashes, NUL.
  if (key.includes("..") || key.startsWith("/") || key.includes("\\"))
    return false;
  if (key.includes("\0") || key.includes("//")) return false;
  return KEY_PATTERN.test(key);
}
