import { GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { env } from "./env";

/**
 * S3-compatible storage (SPEC §9). MinIO in dev, Railway MinIO in production —
 * the same API either way.
 *
 * The bucket is PRIVATE and has no public policy. Nothing here ever hands the
 * storage host to a browser: `/api/media/[...key]` STREAMS the bytes through our
 * own origin. It used to 302 to a presigned URL, which handed the storage host
 * to the browser and was blocked outright by `img-src 'self'` (see the route).
 *
 * Server-only: this module reads credentials and must never be imported from a
 * client script (AGENT §4).
 */
const client = new S3Client({
  region: env.S3_REGION,
  endpoint: env.S3_ENDPOINT,
  // MinIO serves buckets as path segments rather than subdomains.
  forcePathStyle: env.S3_FORCE_PATH_STYLE,
  credentials: {
    accessKeyId: env.S3_ACCESS_KEY_ID,
    secretAccessKey: env.S3_SECRET_ACCESS_KEY,
  },
});

/**
 * How long a browser may cache a media response.
 *
 * A full year, and safe to be: keys are `projects/{projectId}/{ulid}-{width}.{ext}`
 * (SPEC §9), so a key names one immutable object — new bytes get a new ULID and
 * therefore a new URL. `immutable` tells the browser not to revalidate at all.
 *
 * This is the number the presigned-redirect design could not have. There, the
 * cache lifetime had to stay strictly BELOW the 5-minute signature TTL, or a
 * cached 302 replayed a `Location` whose signature had expired and the image
 * 403'd. SPEC §9 asks for "a 5-minute TTL AND a long Cache-Control", which was
 * unsatisfiable under a redirect and is trivially satisfiable under a proxy —
 * there is no signature left to outlive.
 */
export const MEDIA_CACHE_SECONDS = 31_536_000;

export interface StoredObject {
  body: ReadableStream<Uint8Array>;
  contentLength: number | null;
  etag: string | null;
}

/**
 * Streams one object out of the private bucket.
 *
 * The caller has already proved the key exists in `MediaAsset`; this does not
 * re-authorise. It deliberately does NOT return the storage `Content-Type` —
 * the route serves the `mimeType` recorded on the row, which was sniffed from
 * magic bytes at upload (SPEC §9). Trusting the storage header here would let
 * whatever put an object in the bucket choose the type the browser sniffs.
 */
export async function getObject(
  key: string,
  bucket = env.S3_BUCKET,
): Promise<StoredObject | null> {
  const result = await client.send(
    new GetObjectCommand({ Bucket: bucket, Key: key }),
  );

  if (!result.Body) return null;

  return {
    // The SDK types this as ReadableStream<any>; narrowing it here keeps the
    // `any` from leaking into the route, which is what the lint rule is for.
    body: result.Body.transformToWebStream() as ReadableStream<Uint8Array>,
    contentLength: result.ContentLength ?? null,
    etag: result.ETag ?? null,
  };
}

/**
 * Keys are generated by the upload pipeline (#28) as
 * `projects/{projectId}/{ulid}-{width}.{ext}` — never a client-supplied filename
 * (SPEC §9).
 *
 * This is a shape check, not the authorisation: the route still requires a
 * matching `MediaAsset` row. It exists so a traversal or absolute path is
 * rejected before it can reach the S3 client at all, and so the rejection is
 * cheap. AGENT §3: nothing user-controlled reaches an outbound URL unvalidated.
 */
const KEY_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._/-]*$/;

export function isSafeKey(key: string): boolean {
  if (key.length === 0 || key.length > 512) return false;
  // Traversal, absolute paths, protocol-relative, backslashes, NUL.
  if (key.includes("..") || key.startsWith("/") || key.includes("\\"))
    return false;
  if (key.includes("\0") || key.includes("//")) return false;
  return KEY_PATTERN.test(key);
}
